spring:
  application:
    name: minecraft-backend

  data:
    mongodb:
      uri: mongodb://localhost:27017/minecraft_wiki

mongock:
  migration-scan-package:
    - com.minecraft_wiki.backend.config.migration
  transactions: false

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always