spring:
  application:
    name: minecraft-backend

  data:
    mongodb:
      uri: mongodb://localhost:27017/minecraft_wiki

mongock:
  migration-scan-package:
    - com.minecraft_wiki.backend.config.migration
  transactions: false

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

minecraftServer:
  rcon:
    host: 127.0.0.1
    port: 25575
    password: test_password

s3:
  endpoint: http://localhost:9000
  region: us-east-1
  bucket: minecraft-wiki-images
  access-key: admin
  secret-key: adminadmin